version: "3.3"

# this is for custom docker network (for use multiple docker compose)
networks:
  backend:
    external: true

services:
  cloudflaretunnel:
    container_name: cloudflaretunnel
    image: cloudflare/cloudflared:2023.2.1
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
    command: tunnel --no-autoupdate run
    networks:
      - backend
