version: "3.3"

networks:
  backend:
    external: true

services:
  whoami:
    image: "traefik/whoami"
    # container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`t.on-the-everything.work`)"
      - "traefik.http.routers.whoami.entrypoints=web, websecure"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      # - "traefik.enable=true"
      # - "traefik.http.services.whoami.loadbalancer.server.port=80"
      # - "traefik.http.routers.whoami.entrypoints=web, websecure"
      # - "traefik.http.routers.whoami.rule=Host(`t.on-the-everything.work`)"
      # - "traefik.http.routers.whoami.middlewares=redirect-to-https"
      # - "traefik.http.middlewares.redirect-to-https.headers.sslredirect=true"
      # - "traefik.http.middlewares.redirect-to-https.headers.sslProxyHeaders.X-Forwarded-Proto=https"
      # - "traefik.http.services.whoami.loadbalancer.sticky=true"

      # - traefik.enable=true
      # - traefik.http.routers.whoami.entrypoints=web, websecure
      # - traefik.http.routers.whoami.rule=PathPrefix(`/ex-prefix`) && Host(`t.on-the-everything.work`)
      # - traefik.http.services.whoami.loadbalancer.server.port=80
      # - traefik.http.routers.whoami.tls=true
      # - traefik.http.routers.whoami.tls.certresolver=myresolver
      # - traefik.http.routers.whoami.middlewares=st
      # - traefik.http.middlewares.st.stripprefix.prefixes=/ex-prefix

    networks:
      - backend